name: Deploy
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
          echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -av --delete -e 'ssh -i ./deploy_key' dist/ "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/katie/website"
